# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - task: GitVersion@5
    inputs:
      runtime: 'core'

  - task: JsonPatch@3
    inputs:
      JsonWorkingDir: '.'
      SyntaxType: 'slick'
      JsonTargetFilters: 'package.json'
      JsonPatchContent: '= /version => "$(GitVersion.NuGetVersion)"'
      OutputPatchFile: true
      FailIfNoPatchApplied: true
      TreatErrors: 'ERROR'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: CopyFiles@2
    inputs:    
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        dist/**/*
        package.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy build to artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'publish artifacts'
